server:
  port: 8888

spring:
  application:
    name: gscores
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:gsdb}?reWriteBatchedInserts=true
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:gsuser}
    password: ${DB_PASSWORD:gspassword}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

data:
  file-path: classpath:data/diem_thi_thpt_2024.csv